-- MySQL Script generated by MySQL Workbench
-- Mon Apr 19 10:16:17 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Гос.Заказ.Челяб
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Гос.Заказ.Челяб
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Гос.Заказ.Челяб` DEFAULT CHARACTER SET utf8 ;
USE `Гос.Заказ.Челяб` ;

-- -----------------------------------------------------
-- Table `Гос.Заказ.Челяб`.`Статус пользователя`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Гос.Заказ.Челяб`.`Статус пользователя` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Статус пользователя` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Гос.Заказ.Челяб`.`Отделы`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Гос.Заказ.Челяб`.`Отделы` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Название отделы` VARCHAR(45) NULL,
  `Количество человек` VARCHAR(45) NULL,
  `Отчет` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Гос.Заказ.Челяб`.`Отдел заявок`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Гос.Заказ.Челяб`.`Отдел заявок` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Отделы_id` INT NOT NULL,
  `Номер заявки` VARCHAR(45) NULL,
  `Приоритет` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Отдел заявок_Отделы1_idx` (`Отделы_id` ASC) VISIBLE,
  CONSTRAINT `fk_Отдел заявок_Отделы1`
    FOREIGN KEY (`Отделы_id`)
    REFERENCES `Гос.Заказ.Челяб`.`Отделы` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Гос.Заказ.Челяб`.`Заказы`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Гос.Заказ.Челяб`.`Заказы` (
  `id` INT NOT NULL,
  `Отдел заявок_id` INT NOT NULL,
  `Имя` VARCHAR(45) NULL,
  `Фамилия` VARCHAR(45) NULL,
  `Отчество` VARCHAR(45) NULL,
  `Коментарий` VARCHAR(45) NULL,
  `Статус` VARCHAR(45) NULL,
  `Приоритет` VARCHAR(45) NULL,
  `Сумма` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Заказы_Отдел заявок1_idx` (`Отдел заявок_id` ASC) VISIBLE,
  CONSTRAINT `fk_Заказы_Отдел заявок1`
    FOREIGN KEY (`Отдел заявок_id`)
    REFERENCES `Гос.Заказ.Челяб`.`Отдел заявок` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Гос.Заказ.Челяб`.`Пользователи`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Гос.Заказ.Челяб`.`Пользователи` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Статус пользователя_id` INT NOT NULL,
  `Заказы_id` INT NOT NULL,
  `Логин` VARCHAR(45) NULL,
  `Пароль` VARCHAR(45) NULL,
  `Фамилия` VARCHAR(45) NULL,
  `Имя` VARCHAR(45) NULL,
  `Отчество` VARCHAR(45) NULL,
  `ИНН` VARCHAR(45) NULL,
  `Заявка` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Пользователи_Статус пользоват_idx` (`Статус пользователя_id` ASC) VISIBLE,
  INDEX `fk_Пользователи_Заказы1_idx` (`Заказы_id` ASC) VISIBLE,
  CONSTRAINT `fk_Пользователи_Статус пользовате`
    FOREIGN KEY (`Статус пользователя_id`)
    REFERENCES `Гос.Заказ.Челяб`.`Статус пользователя` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Пользователи_Заказы1`
    FOREIGN KEY (`Заказы_id`)
    REFERENCES `Гос.Заказ.Челяб`.`Заказы` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Гос.Заказ.Челяб`.`Активы`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Гос.Заказ.Челяб`.`Активы` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Номер кабинета` VARCHAR(45) NULL,
  `Номер отдела` VARCHAR(45) NULL,
  `Отделы_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Активы_Отделы1_idx` (`Отделы_id` ASC) VISIBLE,
  CONSTRAINT `fk_Активы_Отделы1`
    FOREIGN KEY (`Отделы_id`)
    REFERENCES `Гос.Заказ.Челяб`.`Отделы` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Гос.Заказ.Челяб`.`Гос.Бюджет`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Гос.Заказ.Челяб`.`Гос.Бюджет` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Дата` VARCHAR(45) NULL,
  `Время` VARCHAR(45) NULL,
  `Сумма` VARCHAR(45) NULL,
  `Счет` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Гос.Заказ.Челяб`.`Администраторы`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Гос.Заказ.Челяб`.`Администраторы` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Гос.Бюджет_id` INT NOT NULL,
  `Отделы_id` INT NOT NULL,
  `Роль` VARCHAR(45) NULL,
  `Фамилия` VARCHAR(45) NULL,
  `Имя` VARCHAR(45) NULL,
  `Отчество` VARCHAR(45) NULL,
  `Администраторыcol` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Администраторы_Гос.Бюджет1_idx` (`Гос.Бюджет_id` ASC) VISIBLE,
  INDEX `fk_Администраторы_Отделы1_idx` (`Отделы_id` ASC) VISIBLE,
  CONSTRAINT `fk_Администраторы_Гос.Бюджет1`
    FOREIGN KEY (`Гос.Бюджет_id`)
    REFERENCES `Гос.Заказ.Челяб`.`Гос.Бюджет` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Администраторы_Отделы1`
    FOREIGN KEY (`Отделы_id`)
    REFERENCES `Гос.Заказ.Челяб`.`Отделы` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
